/*
 Copyright © 1995, 2021, Oracle and/or its affiliates. All rights reserved.

 For information, please see the following link:
 https://www.oracle.com/legal/copyright.html

 Oracle Infinity
 @preserve Copyright (c) 2017, 2018, 2019, Oracle and/or its affiliates. All rights reserved.
 odc.js v1.0.7
 Created: 2023-11-14T12:16:27+0000

 Oracle Personalization Module
 Copyright (c) 2022, 2023 Oracle and/or its affiliates. All rights reserved.
 personalization.js branch #master and build #1.1.0.3
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.createTemplateTagFirstArg=function(k){return k.raw=k};$jscomp.createTemplateTagFirstArgWithRaw=function(k,n){k.raw=n;return k};$jscomp.getRestArguments=function(){for(var k=Number(this),n=[],r=k;r<arguments.length;r++)n[r-k]=arguments[r];return n};
(function(){function k(x,t){var A={major:1,minor:0,inc:7},h=this,I=!1,G=2E3,E="sizzle",W=null,V=!1,J=!1,S=!1,m={};this.getTagId=function(){return"media_bu"};this.inHead=function(){return J};this.applyStyleSheet=function(a,b){try{var c=t.getElementsByTagName("head")[0],d=t.createElement("style");d.type="text/css";d.id=b;d.styleSheet?d.styleSheet.cssText=a:d.appendChild(t.createTextNode(a));c.appendChild(d)}catch(f){ORA.Debug.error("applyStyleSheet:  Failed to failed to apply stylesheet","004",f)}};
this.removeStyleSheet=function(a){try{var b=t.getElementById(a);"undefined"!==typeof b&&null!==b&&b.parentNode.removeChild(b)}catch(c){ORA.Debug.debug("removeStyleSheet:  Failed to remove stylesheet")}};this.getSelector=function(){if("sizzle"===E){if("undefined"!==typeof Sizzle&&ORA.hasVal(Sizzle))return Sizzle;if("undefined"!==typeof ORA.Sizzle)return ORA.Sizzle}else{if(null!==W)return W;ORA.Debug.error("getSelector:  No Selector found","003")}return!1};this.setCustomSelector=function(a,b){E=a;W=
b};this.hasVal=function(a){return null!==a&&"undefined"!==typeof a};var Z=function(a,b,c){a=h.hasVal(a)&&"shift"!==b&&!J;b=h.hasVal(b);c=h.hasVal(c);return a&&b&&c},aa=function(a,b,c){var d="hideAndShow:  ";d=J?d+"tag inHead":d+"tag not inHead";d=c?d+", showing":d+", hiding";d=a&&a.nodeName?d+(", "+a.nodeName):d+", unnamed elem";return d+('"  with type "'+b+' "')},ba=function(a,b,c){J?a("body{ display: none !important}"):(b.style.display="",c&&(b.style.display="none"),b===t.body||c||(t.body.style.display=
""))},ca=function(a,b,c){J?a("body{ visibility: hidden !important}"):(b.style.visibility="visible",c||(b.style.visibility="hidden"),b.style.hidden=!c,b===t.body||c||(t.body.style.visibility="visible",t.body.style.hidden=!1))},da=function(a,b,c){c?(a=t.getElementById("ora_shiftStyle"))&&a.parentNode.removeChild(a):(a=t.getElementsByTagName("head")[0],b=t.createElement("style"),b.type="text/css",b.id="ora_shiftStyle",b.styleSheet?b.styleSheet.cssText="body{position:absolute !important; left: -1000% !important; visibility: hidden}":
b.appendChild(t.createTextNode("body{position:absolute !important; left: -1000% !important;}")),a.appendChild(b))},ea=function(a,b,c,d){b=t.getElementById("ora_overlay");var f=t.getElementById("ora_overlayStyle");a=d;h.hasVal(d)&&(a="#ffffff");c&&b?(b.parentNode.removeChild(b),f&&f.parentNode.removeChild(f)):c||b||(J&&h.Debug.error("hideAndShow: Warning! tag detected in head, overlay mode may error out or cause flickering","007"),f||(c=t.createElement("style"),c.setAttribute("type","text/css"),c.setAttribute("id",
"ora_overlayStyle"),a="#ora_overlay{position:absolute;width:100%;height:100%;top:0px;right:0px;bottom:0px;left:0px;background-color:"+(a+";z-index:2147483646}"),c.styleSheet?c.styleSheet.cssText=a:c.appendChild(t.createTextNode(a)),t.getElementsByTagName("head")[0].appendChild(c)),h.hasVal(d)?b=t.createElement("div"):(b=t.createElement("iframe"),b.frameBorder=0),b.id="ora_overlay",t.getElementsByTagName("body")[0].appendChild(b))};this.hideAndShow=function(a,b,c){try{if(Z(a,b,c)){h.Debug.debug(aa(a,
b,c));var d=function(f){c?h.removeStyleSheet("o_style"):h.applyStyleSheet(f,"o_style")};switch(b){case "display":ba(d,a,c);break;case "visibility":ca(d,a,c);break;case "shift":case "supershift":da(d,a,c);break;case "overlay":ea(d,a,c);break;case "none":ORA.Debug.trace("LOADER: type: none");break;default:h.Debug.debug("hideAndShow did not contain a matching type, so not hiding/showing")}d={};d.displayType=b;d.display=c;h.fireEvent(new ORA.Event(ORA.Event.HIDESHOW,ORA.Event.STATUS_SUCCESS,a,d))}else h.Debug.error("hideAndShow param list incomplete",
"006")}catch(f){h.Debug.error("Failure in hide/show functionality.  Verify valid HTML syntax","008",f)}};J=function(){try{var a=t.getElementsByTagName("script");return"HEAD"===a[a.length-1].parentNode.nodeName}catch(b){return WT.Debug.error("inHead: Failed to detect if in head, assuming inHead","001",b),!0}}();var H=function(){V||(V=!0,ORA.fireEvent(new ORA.Event(ORA.Event.DOM_READY,ORA.Event.STATUS_SUCCESS),!0))},y=function(){S||(S=!0,ORA.fireEvent(new ORA.Event(ORA.Event.DOM_ONLOAD,ORA.Event.STATUS_SUCCESS),
!0))},K=function(a){for(var b=document.cookie.split(";"),c=0;c<b.length;c++){var d=[];d[0]=b[c].substring(0,b[c].indexOf("\x3d"));for(d[1]=b[c].substring(b[c].indexOf("\x3d")+1);" "===d[0].charAt(0);)d[0]=d[0].substring(1,d[0].length);if(d[0]===a)return d[1]}return null},O=function(a){for(var b=document.getElementsByTagName("meta"),c=0;c<b.length;c++)if(b[c].name===a)return b[c].content;return null};this.execute=function(a){Array.prototype.slice.call(arguments,1);fireEventName(ORA.Event.LOADER_PRE_EXECUTE,
a);fireEventName(ORA.Event.LOADER_EXECUTE,a)};this.loaderConversionTimeoutDefault=function(){return G};this.setLoaderConversionTimeoutDefault=function(a){G=a};this.reset=function(){for(var a in m)m.hasOwnProperty(a)&&m[a].reset();fireEventName(ORA.Event.LOADER_RESET,null)};this.pollForCondition=function(a,b,c){var d=200,f=function(g,e,q,p,z){window.setTimeout(function(){d--;g()?(h.Debug.trace("pollForCondition success result\x3d"+g(),"LOADER"),h.Debug.superfine("pollForCondition success condition\x3d"+
g.toString(),"LOADER"),e&&(e(),h.Debug.trace("pollForCondition running callback","LOADER"),h.Debug.superfine("pollForCondition callback\x3d"+e.toString(),"LOADER"))):0<d?(h.Debug.trace("LOADER:  pollForCondition timeoutCount\x3d"+d),f(g,e,q,d)):(h.Debug.error("pollForCondition Fail on "+g.toString(),"009"),q&&(q(),h.Debug.superfine("pollForCondition callbackFailure\x3d"+q.toString(),"LOADER")))},z)};f(a,b,c,d,5)};this.paramsMerge=function(a,b,c){var d={};if(ORA.hasVal(a))for(var f in a)a.hasOwnProperty(f)&&
(d[f]=a[f]);for(var g in b)ORA.hasVal(b[g])&&b.hasOwnProperty(g)&&(ORA.hasVal(c)&&ORA.hasVal(c[g])?d[g]=c[g]:d[g]=b[g]);return d};this.downloadLib=function(a,b,c,d,f,g){g&&(h.Debug.info("LOADER:  Start download: https:"+g+" \x26 attach to "+a+", async\x3d"+f),window.setTimeout(function(){var e=t.getElementsByTagName(a)[0],q=t.createElement("script");q.type="text/javascript";q.src="https:"+g;q.setAttribute("async",f);q.setAttribute("defer",f);q.oraHasRun=!1;var p=function(){!1===this.oraHasRun?(b(),
this.oraHasRun=!0,h.Debug.info("Completed download: https:"+g+", callback running oraHasRun\x3d"+this.oraHasRun,"LOADER"),h.Debug.superfine("downloadLib: successCallback\x3d"+b.toString(),"LOADER")):h.Debug.trace("downloadLib: not running successCallback, since oraHasRun\x3d"+this.oraHasRun,"LOADER")};b&&(q.onload=p,q.onreadystatechange=p);q.onerror=function(){h.Debug.error("FAILED download: https:"+g+" \x26 attach to "+a+", async\x3d"+f,"010");c&&(c(),h.Debug.superfine("failCallback: "+c.toString(),
"LOADER"))};"undefined"!==typeof e?e.appendChild(q):h.Debug.info("LOADER:  Dom element: "+a+" is not found so not Downloading")},d))};this.downloadLibs=function(a,b,c,d,f){if("undefined"===typeof f)h.Debug.info("LOADER:  downloadLibs srcs is empty");else{var g={},e=function(p){return function(){g[p]="complete";h.Debug.trace("LOADER:  downloadLibs is complete src:"+p+" \x3d "+f[p])}},q;for(q in f)f.hasOwnProperty(q)&&(g[q]="waiting",h.Debug.trace("LOADER:  downloadLibs is waiting on src:"+q+" \x3d "+
f[q]),h.downloadLib(a,e(q),null,c,d,f[q]));h.pollForCondition(function(){for(var p in g)if(g.hasOwnProperty(p)&&"complete"!==g[p])return!1;return!0},function(){h.Debug.debug("LOADER:  downloadLibs completed on all downloads");b()})}};this.parseQueryString=function(a){var b=a;h.hasVal(a)&&h.hasVal(a.location)&&h.hasVal(a.location.search)||(b=document);a=function(c){var d=c.split("\x26"),f={};null!==d&&0===d.length&&(d=c.split(";"));if(null===d)return f;c=0;d&&(c=d.length-1);for(var g=0;g<=c;g++){var e=
d[g].split("\x3d");e[0]=unescape(e[0]);e[1]=unescape(e[1]);e[0]=e[0].replace(/\+/g," ");e[1]=e[1].replace(/\+/g," ");e[1]=e[1].replace(/<.*\?>/g,"");f[e[0]]=e[1]}return f};return b.location.search?(b=b.location.search.substring(1,b.location.search.length),a(b)):b.location.href?(b=b.location.href.split("?"),2===b.length?a(b[1]):null):null};this.abortModuleHelper=function(a,b){ORA.fireEvent(new ORA.Event(a+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS));ORA.setExecuteState(a,ORA.Event.LOADER_MODULE_ABORT);
ORA.Debug.error("Aborting product: "+a,"011");ORA.Debug.error("LOADER Error","011",b)};this.Event=function(a,b,c,d){a&&(a=a.toLowerCase());this.name=a;this.handler=null;this.state=ORA.Event.STATUS_UNKNOWN;b&&(this.state=b);this.target=c;this.params={};d&&(this.params=d)};this.fireEventName=function(a,b){ORA.fireEvent(new ORA.Event(a,ORA.Event.STATUS_SUCCESS,null,b),null,null,!0)};this.EventEngineClass=function(){var a={},b={},c=function(g,e,q,p){I&&!p&&h.Debug.error("fireEvent: Loader global abort, Aborted due to prior error",
"012",null,"LOADER");e.handler=g;e.params.eventID=(new Date).getTime();p="not set";q&&(p=q);h.Debug.trace("fireEvent: [name: "+e.name+"], state:"+e.state+"async["+p+"]","LOADER");h.Debug.superfine("function:"+e.handler.toString()+"]","LOADER");q?window.setTimeout(function(z,B){return function(){z(B)}}(g,e),0):e.handler(e);return 1},d=function(g,e,q,p,z){for(var B=0;B<b[g][z].length;B++)if(h.hasVal(b[g][z][B])&&b[g][z][B].toString()===p.toString()&&!0!==e){q=!0;break}q||(b[g][z].push(p),e="addEventHandler success handler"+
b[g][z].length,e+=" for "+g+"\nhandler\x3d"+p.toString(),h.Debug.superfine(e,"LOADER"));return q};a.addEventHandler=function(g,e,q,p){var z=g;g=0;var B=!1;if(!z||!e&&!q)return h.Debug.debug("events: Can not add event handler, missing name or listeners. ","LOADER"),-1;var F=z=z.toLowerCase();b[F]||(b[F]={});b[F].success||(b[F].success=[]);b[F].fault||(b[F].fault=[]);e&&(B=d(z,p,!1,e,"success"));B||(g=1);q&&(B=d(z,p,!1,q,"fault"));B||(g+=1);p=z;if(b[p].queue&&0!==b[p].queue.length)for(z=b[p].queue.length-
1;0<=z;z--)B=b[p].queue[z],e&&"success"===B.event.state?c(e,B.event,B.async,B.override):q&&"fault"===B.event.state&&c(q,B.event,B.async,B.override),b[p].queue.splice(z,1);return g};var f=function(g,e,q){for(var p=0;p<b[g][q].length;p++)if(h.hasVal(b[g][q][p])&&b[g][q][p].toString()===e.toString())return b[g][q].splice(p,1),1;return 0};a.removeEventHandler=function(g,e,q){if(!g)return h.Debug.trace("LOADER removeEventHandler:  events: Can not remove event handler, missing event name."),-1;g=g.toLowerCase();
if(!b[g])return 0;if(!e&&!q)return delete b[g],0;var p=0;e&&(p+=f(g,e,"success"));q&&(p+=f(g,q,"fault"));return p};a.fireEvent=function(g,e,q,p){if(I&&!q)return h.Debug.error("fireEvent: Loader global abort, Aborted due to prior error","012",null,"LOADER"),g.name?h.Debug.error("fireEvent(event\x3d"+g.name+"): g_loaderAborted due to prior error","012",null,"LOADER"):h.Debug.error("fireEvent: Aborted due to prior error, check error message for details.","012"),-1;var z=g.name,B=g.state;var F=!!b[z],
T=!(!F||!b[z][B]),Y=!(!F||!b[z].queue);T&&0!==b[z][B].length||!p?F?T?p=1:(h.Debug.trace("fireEvent: [name:"+z+", state:"+B+"] no event handler was found","LOADER"),p=-1):(h.Debug.trace("fireEvent: [name: "+z+"], no registered event was found","LOADER"),p=-1):(h.Debug.trace("fireEvent: [name: "+z+"], no registered event was found, enqueueing","LOADER"),F||(b[z]={}),Y||(b[z].queue=[]),b[z].queue.push({event:g,async:e,override:q}),p=0);if(0>=p)return p;p=b[z][B];for(T=F=0;T<p.length;T++)if(p[T])try{c(p[T],
g,e,q),F++}catch(fa){Y="Unhandled Event Exception, [name: "+z+", state: "+B+", function: ",Y+=g.handler.toString()+"]",h.Debug.error(Y,"013",fa)}return F};a.getEventHandlers=function(){return b};a.length=function(){var g=0,e;for(e in b)b.hasOwnProperty(e)&&g++;return g};a.addFireOnce=function(g,e,q){var p=function(){e();a.removeEventHandler(g,p,q)};a.addEventHandler(g,p,q)};a.clearAllEventHandlers=function(){b={}};return a};var P=new this.EventEngineClass;this.addEventHandler=P.addEventHandler;this.removeEventHandler=
P.removeEventHandler;this.fireEvent=P.fireEvent;this.addFireOnce=P.addFireOnce;this.clearAllEventHandlers=P.clearAllEventHandlers;this.Event.PREINIT="preinit";this.Event.INIT="init";this.Event.PRELOAD="preload";this.Event.LOAD="load";this.Event.POSTLOAD="postload";this.Event.LOADER_ABORT="loader_abort";this.Event.LOADER_MODULE_ABORT="loader_module_abort";this.Event.DEBUGGER_CLEAR_COOKIES="debugger_clear_cookies";this.Event.DEBUGGER_DUMP_PARAMS="debugger_dump_params";this.Event.DEBUG_ERROR_OUT="debug_error_out";
this.Event.DOM_READY="dom_ready";this.Event.DOM_ONLOAD="dom_onload";this.Event.TIMER_EXPIRE="timer_expire";this.Event.TIMER_CLEAR="timer_clear";this.Event.STATUS_SUCCESS="success";this.Event.STATUS_FAULT="fault";this.Event.STATUS_UNKNOWN="unknown";this.Event.PAGEVIEW="pageview";this.Event.CONVERSION="conversion";this.Event.DEBUGGER_CHECK_MODE="debugger_check_mode";this.Event.SCRIPT_LOAD_COMPLETE="script_load_complete";this.Event.HIDESHOW="hide_show";this.Event.SET_CLIENT_ID="set_client_id";this.Event.CLEAR_CLIENT_ID=
"clear_client_id";this._Debug=function(){var a=-1;this._shutdown=!1;var b=[],c=this,d=function(f,g,e){e&&(g=e+":  "+g);if(!(a<f)&&"undefined"!==typeof console&&console){e=!0;switch(f){case 0:console.error&&(console.error(g),e=!1);break;case 1:console.warn&&(console.warn(g),e=!1);break;case 2:console.info&&(console.info(g),e=!1);break;case 3:case 4:case 5:console.log&&(console.log(g),e=!1)}!0===e&&console.log&&console.log(g)}};c.superfine=function(f,g){d(5,f,g)};c.trace=function(f,g){d(4,f,g)};c.debug=
function(f,g){d(3,f,g)};c.info=function(f,g){d(2,f,g)};c.error=function(f,g,e,q){var p="";e&&("string"===typeof e?p="\n"+e:e.toString?(p=e.toString(),e.stack&&(p+=", [stack]: "+e.stack)):p=e.message?e.name?e.fileName?"\n"+e.message+" ["+e.name+"]\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:"\n"+e.message+" ["+e.name+"]":e.fileName?"\n"+e.message+"\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:"\n"+e.message:e.name?e.fileName?"\n ["+e.name+"]\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:"\n ["+
e.name+"]":e.fileName?"\n\n ("+e.fileName+":"+e.lineNumber+")\n"+e.stack:"\n");d(0,(g?g+": ":"")+f+p,q);ORA.fireEvent(new ORA.Event(ORA.Event.DEBUG_ERROR_OUT,ORA.Event.STATUS_SUCCESS,e))};c.dir=function(f,g,e){g&&d(2,g,e);console&&"function"===typeof console.dir?console.dir(f):c.dirStr(f)};c.dirStr=function(f,g){var e=f||{},q=g||"",p;for(p in e)e.hasOwnProperty(p)&&"function"!==typeof e[p]&&c.debug("\t"+p+" : "+e[p],q)};c.setDebugLevel=function(f){a=f};c.getDebugLevel=function(){return a};c.dumpParams=
function(){var f=c.getConfigParams(),g;for(g in f)f.hasOwnProperty(g)&&"object"===typeof f[g]&&c.dir(f[g],"Config parameters",g);return f};c.getConfigParams=function(){var f={};f.loader={version:A,versionStr:[A.major,A.minor,A.inc].join(".")};return f};c.checkMode=function(f){ORA.fireEvent(new ORA.Event(ORA.Event.DEBUGGER_CHECK_MODE,ORA.Event.STATUS_SUCCESS,{resetFlag:f}))};c.getHistory=function(){return b}};var M=function(a,b){this._name=a;this._state=b;this._met=!1},D=function(a,b,c){var d=this,
f={},g=[];this.prodId=a;this.plugin=new b;this.executeState=D.WAITING;this.stopTime=this.startTime=this.timer=null;this.configName="default";"undefined"!==typeof c&&(this.configName=c);this.putDependency=function(e){f[e._name]=e};this.reset=function(){d.executeState=D.WAITING;f={};g=[]};this.clearDependencies=function(){f={}};this.getDependency=function(e){for(var q in f)if(f.hasOwnProperty(q)&&f[q]._name===e)return f[q];return null};this.getDependents=function(){0===g.length&&(g=ORA.getDependents(d.prodId));
return g};this.updateDependents=function(){g=ORA.getDependents(d.prodId)};this.getExecuteState=function(){return this.executeState};this.hasMetDeps=function(){for(var e in f)if(f.hasOwnProperty(e)&&""!==e&&!0!==f[e]._met)if(m[e].getExecuteState()===f[e]._state)f[e]._met=!0;else return!1;return!0};this.updateDependencyState=function(e,q){var p=d.getDependency(e);null!==p&&p._state===q&&(p._met=!0)};this._startTimer=function(e){this.timer?h.Debug.info("LOADER:  "+this.prodId+" timer already started, using current timer."):
(h.Debug.debug("LOADER:  starting timer for "+d.prodId),this.timer=window.setTimeout(function(){h.Debug.error("LOADER:  "+d.prodId+"module timer expired calling Abort","015");h.fireEvent(new ORA.Event(d.prodId+"_"+ORA.Event.TIMER_EXPIRE,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(d.prodId+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},e),this.startTime=new Date,h.Debug.info("LOADER:  "+this.prodId+" timer started ["+this.startTime+"]."))};this._clearTimer=function(){this.stopTime=
new Date;this.timer&&(clearTimeout(this.timer),this.timer=null);h.Debug.info("LOADER:  "+this.prodId+" timer cleared ["+this.stopTime+"]")};this.tryExecPostload=function(){var e=d.getExecuteState()===D.READY,q=d.hasMetDeps(),p=void 0!==d.plugin[ORA.Event.POSTLOAD];if(q&&e&&p)return h.Debug.debug("setExecuteState:  "+d.prodId+" has met all dependencies \x26\x26 ready, running postload"),d.plugin[ORA.Event.POSTLOAD](),!0;if(q&&e)return ORA.Debug.superfine(d.prodId+", has no postLoad section"),!0;ORA.Debug.superfine(d.prodId+
", did not meet postload exec conditionals");return!1}};D.WAITING="waiting";D.DOWNLOADING="downloading";D.READY="ready";D.RUNNING="running";D.ABORTED="aborted";this.registerPlugin=function(a,b){m[a.ProductName]=new D(a.ProductName,a,b);m[a.ProductName].executeState=D.WAITING;ORA.hasVal(a.prototype.abort)&&ORA.addEventHandler(a.ProductName+"_"+ORA.Event.LOADER_MODULE_ABORT,a.prototype.abort);if(ORA.hasVal(a.prototype.oraConfigObj)&&ORA.hasVal(a.prototype.oraConfigObj.s_dependencies))for(var c=a.prototype.oraConfigObj.s_dependencies.split(","),
d=0;d<c.length;d++){var f=c[d].split(":");m[a.ProductName].putDependency(new M(f[0],f[1]))}for(var g in m)m.hasOwnProperty(g)&&m[g].updateDependents();a.prototype&&a.prototype.oraConfigObj&&a.prototype.oraConfigObj.s_useTrackingPipeline&&!0===a.prototype.oraConfigObj.s_useTrackingPipeline&&(m[a.ProductName].useTrackingPipeline=!0,c=a.prototype.oraConfigObj,ORA.hasVal(c.s_pageTimeout)&&ORA.hasVal(c.s_TrackingPipelineTimeout)?m[a.ProductName].s_TrackingPipelineTimeout=Math.max(c.s_pageTimeout,c.s_TrackingPipelineTimeout):
ORA.hasVal(c.s_pageTimeout)?m[a.ProductName].s_TrackingPipelineTimeout=c.s_pageTimeout:ORA.hasVal(c.s_TrackingPipelineTimeout)&&(m[a.ProductName].s_TrackingPipelineTimeout=c.s_TrackingPipelineTimeout))};this.clearPlugins=function(){m={}};this.hasMetDeps=function(a){return m[a].hasMetDeps()};this.getDependents=function(a){var b=[],c;for(c in m)m.hasOwnProperty(c)&&null!==m[c].getDependency(a)&&b.push(c);return b};this.updateDependencies=function(a,b){if(!a||!m[a])return null;if(!b)return m[a].clearDependencies(),
null;var c=b.split(",");if(!c||0===c.length)return null;m[a].clearDependencies();for(var d=0;d<c.length;d++){var f=c[d].split(":");if(2===f.length)m[a].putDependency(new M(f[0],f[1]));else break}return null};var X=function(a){var b=m[a];if(b.tryExecPostload()){b.executeState="running";a=b.getDependents(a);for(var c in a)a.hasOwnProperty(c)&&X(a[c])}};this.setExecuteState=function(a,b){if(b===ORA.Event.LOADER_MODULE_ABORT)m[a].executeState=D.ABORTED;else if(h.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT){m[a].executeState=
b;h.Debug.trace("setExecuteState:  "+a+" to "+b);var c=m[a].getDependents(),d;for(d in c)c.hasOwnProperty(d)&&m.hasOwnProperty(c[d])&&m[c[d]].updateDependencyState(a,b);X(a)}};this.getExecuteState=function(a){return ORA.hasVal(m[a])?m[a].executeState===D.ABORTED?ORA.Event.LOADER_MODULE_ABORT:m[a].executeState:null};this.isDependency=function(a){for(var b in m)if(m.hasOwnProperty(b)&&null!==m[b].getDependency(a))return h.Debug.trace("isDependency:  "+a+" is dependency of "+b),!0;h.Debug.trace("isDependency:  "+
a+" is not a dependency of any product");return!1};this.getTrackingPipelineProducts=function(){var a=[],b;for(b in m)if(m.hasOwnProperty(b)&&m[b].useTrackingPipeline){var c={};c.name=b;m[b].s_TrackingPipelineTimeout&&(c.timeout=m[b].s_TrackingPipelineTimeout);a.push(c)}return a};this.getContextUrl=function(a,b){return"//d.oracleinfinity.io/infy/acs/account/3635138d8e594c2c1be5bc1f505e5b30/js/media_bu/"+a+"-"+b+".js"};this.getProduct=function(a){for(var b in m)if(m.hasOwnProperty(b)&&a===m[b].prodId)return m[b];
return null};this.isProductEnabled=function(a){a+="Module";return ORA[a]&&ORA[a].prototype.oraConfigObj?void 0===ORA[a].prototype.oraConfigObj.enabled?!0:ORA[a].prototype.oraConfigObj.enabled:!1};this.isReady=function(){return V};this.isLoaded=function(){return S};this.addDOMEvent=function(a,b,c){try{return a.addEventListener?a.addEventListener(b,c,!1):a.attachEvent?a.attachEvent("on"+b,c):eval("elm."+b+"\x3dfunc;"),0}catch(d){return-1}};this.removeDOMEvent=function(a,b,c){try{return a.removeEventListener?
a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c),0}catch(d){return-1}};this.getSafeEventName=function(a,b){var c=b.substr(0,2);if(a.addEventListener){if("on"===c)return b.substring(2)}else if(a.attachEvent&&"on"!==c)return"on"+b;return b};var Q=function(){"complete"!==document.readyState&&"undefined"!==typeof document.readyState||H();document.addEventListener("DOMContentLoaded",function(){document.removeEventListener("DOMContentLoaded",arguments.callee,!1);H()},!1);if(/WebKit|Opera/i.test(navigator.userAgent))var a=
setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(a),H())},10)},L=function(){"complete"!==document.readyState&&"loading"!==document.readyState||H();document.attachEvent("onreadystatechange",function(){if("complete"===document.readyState||"loading"===document.readyState)document.detachEvent("onreadystatechange",arguments.callee),H()})},U=function(){try{document.addEventListener&&Q(),document.attachEvent&&L(),window.addEventListener?window.addEventListener("load",function(){window.removeEventListener("load",
arguments.callee,!1);H()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",arguments.callee,!1);H()}),S?y():window.addEventListener?window.addEventListener("load",function(){window.removeEventListener("load",arguments.callee,!1);y()},!1):window.attachEvent&&window.attachEvent("onload",function(){window.detachEvent("onload",arguments.callee,!1);y()})}catch(a){H(),y()}};h.Debug=new h._Debug;var N=this.parseQueryString(x);h.hasVal(N)&&h.hasVal(N["_ora.debug"])&&
h.Debug.setDebugLevel(N["_ora.debug"]);var R=function(a){var b={};a=a.split(/[;,]/);for(var c in a)if(a.hasOwnProperty(c)){var d=a[c].split(":");b[d[0]]=d[1]}return b},l=function(){var a=K("_ora.context");var b=K("_ora.config");a=a||b||null;b=O("_ora.context");var c=O("_ora.config");b=b||c||null;c=N&&(N["_ora.context"]||N["_ora.config"]||null);for(var d=document.getElementsByTagName("SCRIPT"),f,g=/_ora\.context=([^&]*)|_ora\.config=([^&]*)/g,e=0;e<d.length&&!f;e++)d[e].src&&/odc\.js\?/.test(d[e].src)&&
(f=g.exec(d[e].src));if(null!==c)return R(c);if("undefined"!==typeof a&&null!==a)return R(a);if("undefined"!==typeof b&&null!==b)return R(b);if(f&&2<f.length)return void 0!==f[2]?R(f[2]):void 0!==f[1]?R(f[1]):R(f[0])}();if("undefined"!==typeof l){h.Debug.info("LOADER:  Found one or more context(s)");for(var u in l)l.hasOwnProperty(u)&&h.Debug.trace('LOADER:  triggers have set contextTriggerMap "'+u+'":"'+l[u]+'"')}var w=function(a){return"undefined"!==typeof l&&"undefined"!==typeof m[a].configName&&
"undefined"!==typeof l[a]&&l[a]===m[a].configName?(h.Debug.trace('LOADER:  context "'+m[a].configName+'" triggered for '+a),!0):"undefined"===typeof l||"undefined"===typeof l[a]?(h.Debug.trace("LOADER:  published context triggered for "+a),!0):!1},v=function(a){h.Debug.error("Loader Error: "+a,"016")};h.Debug.info("LOADER:  Version "+[A.major,A.minor,A.inc].join("."));this.addEventHandler(this.Event.PREINIT,function(){var a="unknown";try{for(a in m){var b;if(b=m.hasOwnProperty(a)){var c=a;b=ORA.hasVal(m[c].plugin)&&
ORA.hasVal(m[c].plugin[ORA.Event.PREINIT])}b&&w(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=m[a].configName+'" _preinit phase start',h.Debug.trace(c),m[a].plugin[ORA.Event.PREINIT](),c='LOADER:  product "'+a+'" with context name "',c+=m[a].configName+'" _preinit phase complete',h.Debug.trace(c))}}catch(d){ORA.abortModuleHelper(a,d)}},function(){v("preinit fail")});this.addEventHandler(this.Event.INIT,function(){var a="unknown";try{for(a in m){var b;
if(b=m.hasOwnProperty(a)){var c=a;b=ORA.hasVal(m[c].plugin)&&ORA.hasVal(m[c].plugin[ORA.Event.INIT])}b&&w(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=m[a].configName+'" _init phase start',h.Debug.trace(c),m[a].plugin[ORA.Event.INIT](),c='LOADER:  product "'+a+'" with context name "',c+=m[a].configName+'" _init phase complete',h.Debug.trace(c))}}catch(d){ORA.abortModuleHelper(a,d)}},function(){v("init fail")});this.addEventHandler(this.Event.PRELOAD,
function(){var a="unknown";try{for(a in m){var b;if(b=m.hasOwnProperty(a)){var c=a;b=ORA.hasVal(m[c].plugin)&&ORA.hasVal(m[c].plugin[ORA.Event.PRELOAD])&&ORA.hasVal(m[c].plugin.oraConfigObj)&&!0===m[c].plugin.oraConfigObj.doLoad}b&&w(a)&&ORA.getExecuteState(a)!==ORA.Event.LOADER_MODULE_ABORT&&(c='LOADER:  product "'+a+'" with context name "',c+=m[a].configName+'" _preload phase start',h.Debug.trace(c),m[a].plugin[ORA.Event.PRELOAD](),c='LOADER:  product "'+a+'" with context name "',c+=m[a].configName+
'" _preload phase complete',h.Debug.trace(c))}}catch(d){ORA.abortModuleHelper(a,d)}},function(){v("preload fail")});this.addEventHandler(this.Event.LOAD,function(){var a="unknown";try{var b=function(f){return function(){ORA.Debug.debug(f+" downloaded successfully")}},c=function(f){f+="Module";return ORA[f]&&ORA[f].prototype.oraConfigObj&&ORA[f].prototype.oraConfigObj.loadPriority?ORA[f].prototype.oraConfigObj.loadPriority:0},d=function(f){var g;if(g=m.hasOwnProperty(f))g=ORA.hasVal(m[f].plugin)&&
ORA.hasVal(m[f].plugin[ORA.Event.LOAD])&&ORA.hasVal(m[f].plugin.oraConfigObj)&&!0===m[f].plugin.oraConfigObj.doLoad;g&&w(f)&&ORA.getExecuteState(f)!==ORA.Event.LOADER_MODULE_ABORT&&(ORA.setExecuteState(f,D.DOWNLOADING),g='LOADER:  product "'+f+'" with context name "'+(m[f].configName+'" _load phase start'),h.Debug.trace(g),m[f].plugin[ORA.Event.LOAD](b(f)),g='LOADER:  product "'+f+'" with context name "'+(m[f].configName+'" _load phase complete'),h.Debug.trace(g))};for(a in m)m.hasOwnProperty(a)&&
c(a)&&d(a);for(a in m)m.hasOwnProperty(a)&&!c(a)&&d(a)}catch(f){ORA.abortModuleHelper(a,f)}},function(){v("load fail")});this.addEventHandler(this.Event.LOADER_ABORT,function(){var a="unknown";I=!0;h.Debug.error("Loader global abort event","017");try{for(a in m)m.hasOwnProperty(a)&&ORA.hasVal(m[a].plugin)&&!0===m[a].plugin.oraConfigObj.doLoad&&(ORA.fireEvent(new ORA.Event(a+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS),!1,!0),ORA.setExecuteState(a,ORA.Event.LOADER_MODULE_ABORT),ORA.clearTimer(a),
ORA.Debug.error("Aborting product: "+a,"018"))}catch(b){ORA.abortModuleHelper(a,b)}},function(){v("abort fail")});var C=[];this.start=function(){var a=function(){h.fireEvent(new ORA.Event(ORA.Event.PREINIT,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.INIT,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.PRELOAD,ORA.Event.STATUS_SUCCESS));h.fireEvent(new ORA.Event(ORA.Event.LOAD,ORA.Event.STATUS_SUCCESS));h.Debug.debug("LOADER:  Synchronous functionality has finished firing")},
b=function(){for(var c in l)if(l.hasOwnProperty(c)){var d=h.getContextUrl(c,l[c]);"undefined"!==typeof d&&(h.Debug.debug("LOADER:  adding "+d+" to download"),C.push(d))}};try{U(),ORA.hasVal(l)?(h.Debug.debug("LOADER:  contextTriggerMap contains contexts"),b(),h.downloadLibs("head",a,0,!0,C)):a()}catch(c){h.fireEvent(new ORA.Event(ORA.Event.LOADER_ABORT,ORA.Event.STATUS_SUCCESS))}};this.productReady=function(a,b,c){var d=m[a];a=c||a+"_product_ready";if(d&&d.hasMetDeps()&&(d.executeState===D.READY||
d.executeState===D.RUNNING))try{b()}catch(f){ORA.Debug.debug("User supplied product ready callback failed "+f.message)}else d?(ORA.addEventHandler(a,b),ORA.Debug.debug("attached listener for "+a)):(ORA.Debug.debug("product was not found attaching to "+a),ORA.addEventHandler(a,b,null,!0))};this.productReady.push=function(a){ORA.productReady.apply(this,a);ORA.Debug.debug("productReady pushing function for "+a[0],"LOADER")};h.Debug.debug("ORA object created","LOADER");h.Debug.info('To dump config params use: "ORA.Debug.dumpParams()"');
h.Debug.info('To check the mode use: "ORA.Debug.checkMode(false)" - Use true if you wish to reset the mode.')}var n=function(x){var t=[];try{for(;0<x.length;)t=x.shift(),ORA.Debug.debug("productReady queue found when loading for "+t[0],"LOADER"),ORA.productReady.apply(this,t)}catch(A){ORA.Debug.debug("Error processing ORA.productReady queue "+A.message,"LOADER")}};if("undefined"===typeof ORA||"undefined"!==typeof ORA&&!ORA.ready){var r=[];"undefined"!==typeof ORA&&ORA.productReady&&(r=ORA.productReady);
ORA=new k(window,window.document,window.navigator,window.location);n(r);ORA.ready=!0}else console.error("ORA global namespace already in use, Infinity not loaded/setup")})();
(function(){"undefined"!==typeof ORA&&!0===ORA.ready&&(!0===ORA.isInitCompleted?ORA.Debug.error("The tag is being loaded multiple times. Exiting second tag initialization request."):(ORA.isInitCompleted=!0,ORA.registerPlugin=ORA.registerPlugin,ORA.abortModuleHelper=ORA.abortModuleHelper,ORA.setLoaderConversionTimeoutDefault=ORA.setLoaderConversionTimeoutDefault,ORA.loaderConversionTimeoutDefault=ORA.loaderConversionTimeoutDefault,ORA.downloadLib=ORA.downloadLib,ORA.reset=ORA.reset,ORA.productLoadInit=
function(){ORA.personalizationModule=function(){};ORA.personalizationModule.prototype.oraConfigObj={"ora-plugins":{qatool:{enable:!0,dynamic:!0}},enabled:!0,s_dependencies:"",contentAssets:"//d.oracleinfinity.io/infy/personalization/3635138d8e594c2c1be5bc1f505e5b30/production/campaigns.js",edgeServer:"//dc.oracleinfinity.io/display/v1/account/3635138d8e594c2c1be5bc1f505e5b30/state",libUrl:"//d.oracleinfinity.io/infy/acs/account/3635138d8e594c2c1be5bc1f505e5b30/js/media_bu/personalization-production/personalization.js",
accountGuid:"3635138d8e594c2c1be5bc1f505e5b30",tagId:"media_bu",cookieName:"ORA_PERS",alwaysLoad:!0,doLoad:!0,defaultCollectionServer:"dc.oracleinfinity.io",s_useTrackingPipeline:!1,hide:{rule:"body { opacity: .01 !important; pointer-events: none !important; user-select: none !important; }",timeout:1E3},contentAssetsSandbox:"//d.oracleinfinity.io/infy/personalization/3635138d8e594c2c1be5bc1f505e5b30/sandbox/campaigns.js",destinations:[{accountGuid:"3635138d8e594c2c1be5bc1f505e5b30"}]};typeof ORA.personalizationModule.prototype.oraConfigObj.enabled&&
!1===ORA.personalizationModule.prototype.oraConfigObj.enabled?ORA.Debug.debug("personalization  module disabled - exiting module setup"):(ORA.personalizationModule.prototype.preinit=function(){try{ORA.Debug.debug("PREINIT: Executing Preinit script")}catch(k){ORA.abortModuleHelper("personalization",k)}},ORA.personalizationModule.prototype.init=function(){try{this.oraConfigObj.key="value",void 0===this.oraConfigObj.doLoad&&(this.oraConfigObj.doLoad=!0),this.oraConfigObj.doLoad=this.oraConfigObj.doLoad||
this.oraConfigObj.alwaysLoad}catch(k){ORA.abortModuleHelper("personalization",k)}},ORA.personalizationModule.prototype.preload=function(){try{var k=0;ORA.personalizationModule.prototype.oraConfigObj.s_conversionTimeout&&(k=ORA.personalizationModule.prototype.oraConfigObj.s_conversionTimeout);ORA.setLoaderConversionTimeoutDefault(Math.max(k,ORA.loaderConversionTimeoutDefault()));ORA.Debug.debug("PRELOAD:  Executing preload script")}catch(n){ORA.abortModuleHelper("personalization",n)}},ORA.personalizationModule.prototype.load=
function(k){try{ORA.Debug.debug("LOAD:  Executing load phase"),ORA.setExecuteState("personalization","ready"),ORA.Debug.debug("setProductReady()","personalization")}catch(n){ORA.abortModuleHelper("personalization",n)}},ORA.personalizationModule.prototype.postload=function(){ORA.Debug.debug("POSTLOAD:  Executing postload personalization complete");try{ORA.Debug.info("LOADER:  ORA.personalizationModule.prototype: postload"),ORA.personalization.setup()}catch(k){ORA.abortModuleHelper("personalization",
k)}},ORA.personalizationModule.prototype.abort=function(){try{ORA.Debug.debug("ABORT:  Executing personalizationModule abort"),ORA.fireEvent(new ORA.Event(ORA.personalizationModule.ProductName+"_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))}catch(k){ORA.abortModuleHelper("personalization",k)}});(function(k){function n(l,u,w){var v=new XMLHttpRequest;v.open("POST",r(K.edgeServer,N),!0);v.responseType="json";v.setRequestHeader("Content-Type","application/json");v.onreadystatechange=function(){4===
v.readyState&&(200===v.status?u(v.response):w())};v.send(JSON.stringify(l))}function r(l,u){var w=Object.keys(u).map(function(v){return v+"\x3d"+encodeURIComponent(u[v])});w=0===w.length?"":"?"+w.join("\x26");return l+w}function x(){var l=t;var u=new Date;u.setFullYear(u.getFullYear()-1);u=u.toUTCString();l(void 0,"; expires\x3d"+u)}function t(l,u){y.productReady.push(["analytics",function(){L.setCookie(P,JSON.stringify(l),u)}])}function A(l,u){try{return Object.keys(l.campaigns).reduce(function(w,
v){w[v]=l.campaigns[v].activeBlocks.reduce(function(C,a){a:{var b,c;try{if(b=u[v]){var d=v+":"+a;if(!(-1<X.indexOf(d))&&(c=b.blocks[a])){if(h(c.masks,k.location.href)){var f={campaign:{name:b.name},block:{name:c.name},isProduction:!H()},g={html:c.html,css:c.css};X.push(d);c.js(f,g);var e=O.applied}else e=O.ignored;break a}}e=O.disabled}catch(q){k.console.error('Oracle CX Tag caught an error thrown by "'+(b&&b.name)+'" personalization\'s "'+(c&&c.name)+'" node. You should fix the error in its code:\n'+
q.stack),e=O.failed}}C[a]=e;return C},{});return w},{})}catch(w){return y.Debug.error("Error happened during content block application, details: "+w,"P13N"),{}}}function h(l,u){return l&&!I(l.exclude,u)&&I(l.include,u)}function I(l,u){return l&&l.some(function(w){var v=RegExp;w=w.trim().replace(D,"\\$\x26");w=w.replaceAll("*",".*");return(new v("^"+w+"$","gi")).test(u)})}function G(l,u){var w=null,v=null;return function(){var C=$jscomp.getRestArguments.apply(0,arguments),a=this;clearTimeout(v);null===
w?w=setTimeout(function(){l.apply(a,C);w=null},u):v=setTimeout(function(){l.apply(a,C)},u)}}function E(l){if(l)return l&&-1!==l.indexOf("//")?l.replace(/^(http:|https:)/,""):k.location.origin+"/"+l.replace(/^\//,"");y.Debug.error("Content assets url is not defined","P13N")}function W(l,u){return Object.keys(l).find(function(w){return Object.keys(l[w].blocks).find(function(v){return h(l[w].blocks[v].masks,u)})})}function V(){if(J())return x();try{var l=JSON.parse(L.getCookie(P))}catch(u){l={}}n(l,
function(u){A(u,M);t(u,"");Q.show()},function(){A(l,M);Q.show()})}function J(){return"1"===navigator.doNotTrack||"state\x3d1"===L.getCookie("Infinity.optout")}function S(){var l=K.libUrl.replace("personalization.js","qatool.js");y.downloadLib("head",m,Z,0,!0,E(l))}function m(){y.Debug.debug("QA Tool has been loaded","P13N")}function Z(){y.Debug.error("Failed to load QA Tool","P13N")}function aa(){W(M,k.location.href)?(V(),y.productReady.push(["analytics",function(){y.analytics.addMutation("PES",function(l){var u=
l.payload||{};R.map(function(w){u[w]&&(N[w]=u[w])})});y.analytics.addMutation("updateState",G(V,1E3))}])):Q.show()}function ba(){if(H()){var l=U.getState(),u=da(l);u=A(u,M);U.state=ea(l,u);Q.show();S()}else aa();y.Debug.trace("Content assets has been loaded","P13N")}function ca(){y.Debug.error("failure uploading web personalization content","P13N");Q.show();H()&&S()}function da(l){return{campaigns:l.campaigns.reduce(function(u,w){u[w.id]={activeBlocks:w.blocks.filter(function(v){return v.status!==
O.disabled}).map(function(v){return v.id})};return u},{})}}function ea(l,u){return{configuration:l.configuration,campaigns:Object.keys(u).map(function(w){return{id:w,blocks:Object.keys(u[w]).map(function(v){return{id:v,status:u[w][v]}})}})}}function H(){var l=K["ora-plugins"];l=l&&l.qatool&&l.qatool.enable;var u=k.location.search.includes("_ora.pers\x3dqa"),w=L.getCookie("ORA_PERSQA");return l&&(u||w)}var y=k.ORA,K=y.personalizationModule.prototype.oraConfigObj,O={applied:"Applied",ignored:"Ignored",
failed:"Failed",disabled:"Disabled"},P=K.cookieName||"ORA_PERS",M={},D=RegExp("[-[\\]{}()+?.,\\\\^$|#]","g"),X=[],Q=new function(l,u){var w=this,v;this.hide=function(){if(!v&&l&&l.hide&&l.hide.rule&&l.hide.timeout){var C=u.document.getElementsByTagName("head")[0];v=u.document.createElement("style");v.setAttribute("id","iq_personalization_style_hide");v.setAttribute("type","text/css");v.textContent=l.hide.rule;C.insertBefore(v,C.lastChild);u.setTimeout(function(){w.show()},l.hide.timeout)}};this.show=
function(){if(v){var C=u.document.getElementsByTagName("head")[0];C.contains(v)&&C.removeChild(v);v=null}}}(K,k),L=new function(){var l={},u=!1,w;this.setCookie=function(v,C,a){var b=a||"";C=void 0!==C?C:"";var c=y.common&&y.common.clientID&&y.common.clientID.cfg&&y.common.clientID.cfg.cookie||{};if(c.enable){!c.sessionOnly&&c.expireDate instanceof Date&&-1===b.indexOf("expires")&&(b+="; expires\x3d"+c.expireDate.toUTCString());c.autoTLD&&y.plugins&&y.plugins.pp&&y.plugins.pp.Domain&&y.plugins.pp.Domain.getCookieDomain&&
y.plugins.pp.Domain.getCookieDomain()?b+="; domain\x3d"+y.plugins.pp.Domain.getCookieDomain():c.domain&&(b+="; domain\x3d"+c.domain);b+="; path\x3d/";c=!0;y.common&&y.common._getConfigObject()&&!1===y.common._getConfigObject().secureCookie&&(c=!1);var d="; secure";c&&"http:"!==document.location.protocol.toLowerCase()||(d="");document.cookie=v+"\x3d"+C+b+d;y.Debug.debug("setCookie: "+v+" with data: ["+C+"]"+a+d);u=!1}};this.getCookie=function(v){if(!u){if(w=document.cookie)for(var C=w.split(";"),a=
0;a<C.length;a++){var b=C[a].split("\x3d"),c=b.shift().replace(/^\s+|\s+$/g,""),d;1<=b.length&&(d=b.join("\x3d"));b=c;c=d;b.replace(/\s/g,"");l[b]=c}u=!0}y.Debug.debug("getCookie: ["+v+", "+l[v]+"]");return l[v]};this.deleteCookie=function(v){var C="; expires\x3d"+(new Date(0)).toUTCString();this.setCookie(v,null,C);y.Debug.debug("deleteCookie: ["+v+"]")}},U=new function(){this.state=null;this.getState=function(){if(!this.state){var l=L.getCookie("ORA_PERSQA");this.state=l?JSON.parse(l):{configuration:"Sandbox",
campaigns:[]}}return this.state};this.setState=function(l){l?(l=JSON.stringify(l),L.setCookie("ORA_PERSQA",l)):L.deleteCookie("ORA_PERSQA");l=new URLSearchParams(k.location.search);l["delete"]("_ora.pers");l=l.toString();k.location.replace(""+k.location.pathname+(l.length?"?":"")+l)}},N={},R="ora.elq.aid wt.dcsvid rsys.customer_id rsys.riid ora.elq.cid ora.deviceid wt.co_f ora.elq.vid".split(" ");y.personalizationModule.prototype.personalizationCallback=function(l){l&&l.campaigns?M=l.campaigns:y.Debug.error("No web personalization",
"P13N");delete y.personalizationModule.prototype.personalizationCallback};y.personalization={setup:function(){if(J())return x();Q.hide();y.downloadLib("head",ba,ca,0,!0,E((H()?"Sandbox"!==U.getState().configuration:1)?K.contentAssets:K.contentAssetsSandbox))},getConfiguration:function(){return M},getState:function(){return U.getState()},setState:function(l){U.setState(l)},cookieManager:L}})(window);ORA.personalizationModule.ProductName="personalization";ORA.registerPlugin(ORA.personalizationModule,
"production");ORA.analyticsModule=function(){};ORA.analyticsModule.prototype.oraConfigObj={i18n:!1,s_disableSeed:!1,alwaysLoad:!0,enabled:!0,DNTBehavior:"honorDNT",s_dependencies:"common:running",libUrl:"//d.oracleinfinity.io/infy/acs/account/3635138d8e594c2c1be5bc1f505e5b30/js/media_bu/analytics-production/analytics.js",accountGuid:"3635138d8e594c2c1be5bc1f505e5b30",tagId:"media_bu",cookieTypes:"firstpartyonly","ora-plugins":{html5Video:{enable:!0,poll:!1,pctInc:25,beraconType:"auto",seek:!0,load:!0,
cued:!1,loadMeta:!0,postMessage:!1,fixed:!1,quartile:!0,buffering:!1,pollRate:250,nameCallback:null,beaconCurve:{300:30,60:10,600:60,130:30,420:45,1800:150},pause:!0,screenMode:!0,beacon:!0,bins:15,beaconRate:60,metaTags:!0,volume:!0},fingerprint:{enable:!0,addTiming:!0,options:{excludeOpenDatabase:!1,excludeDeviceMemory:!1,excludeHasLiedBrowser:!1,excludeColorDepth:!1,excludeJsFonts:!0,swfContainerId:"",excludeCanvas:!0,excludeDoNotTrack:!1,excludeHasLiedResolution:!1,excludeAudioFP:!1,excludeTimezoneOffset:!1,
swfPath:"",excludeHasLiedLanguages:!1,excludeAvailableScreenResolution:!1,excludeWebGLVendorAndRenderer:!0,excludeLanguage:!1,excludePixelRatio:!1,excludePlatform:!1,excludeUserAgent:!1,excludeHasLiedOs:!1,excludeFlashFonts:!0,excludeAddBehavior:!1,excludeIEPlugins:!1,excludeSessionStorage:!1,excludePlugins:!1,excludeScreenResolution:!1,excludeCpuClass:!1,excludeAdBlock:!1,excludeIndexedDB:!1,excludeWebGL:!0,userDefinedFonts:[],excludeHardwareConcurrency:!1,excludeTouchSupport:!1}},udo:{enable:!0,
UDOName:"dataLayer",addClick:!0,addCommerce:!0},multitrack:{enable:!0},bluekaiUid:{enable:!0,blockCollect:!0},yt:{enable:!0,pctInc:25,seek:!0,pause:!0,load:!0,cued:!1,loadMeta:!0,beacon:!0,mode:"auto",quartile:!0,buffering:!0,loadAPI:!0,bins:15,beaconRate:60,volume:!0},ds:{enable:!0,domains:["webtrends.com","webtrends.co.uk"]},debug:{enable:!0,ignoreparam:!1},blocklist:{enable:!0,allowlist:[],commerce:!0,denylist:["wt.password","wt.user_name","wt.pan","wt.card"],video:!0},pp:{enable:!0,cookieDays:365,
lowerCaseValues:!0,defPrefix:"DCSext",params:"dcsvid infy riid rid customer_id elqCID elqCid elq_cid elq_mid product".split(" "),useMostRecent:!0,cookieName:"WTPERSIST"},plt:{enable:!0,waitTime:150,sampleRate:50,assetFilter:".*js",maxT:2,enablePerf:!1,perfLimit:50},adTracking:{enable:!0,autoCreateAdList:!0,addKey:!0,adsViewedParam:"wt.ad",adKeyParam:"wt.ad_key",sendOnce:!0,adClickParam:"wt.ac",blockCollect:!0},maskIP:{enable:!0},crossDomain:{enable:!0,encode:!0,ignoreOnsiteDoms:!1,guard:"~",denyListSelector:"localhost",
addIdTreatment:"auto",allowListSelector:"A",blockCollect:!0},cg:{enable:!0,cgDefs:["wt.cg_n","wt.cg_s","wt.cg_s2"],blockCollect:!0},mobileBrowser:{enable:!0},evtTrack:{enable:!0,trackSocial:!1,scroll_frequency:25,standardEvents:{anchor:!0,onsite:!0,offsite:!0,rightclick:!0,download:!0,javascript:!0,scrollTracking:!0},downloadtypes:".xls, .doc, .pdf, .txt, .csv, .zip, .docx, .xlsx, .rar, .gzip, .pptx",socialTypes:{}},fragment:{enable:!0,virtualDl:26,virtualPageView:!1,paramHandeling:"none",addAnchorName:"none",
applyClickEventOnly:!1,prefix:"fragment",blockCollect:!0},bc:{enable:!0,poll:!1,seek:!0,load:!0,cued:!1,maxBinds:10,mediaTags:!0,postMessage:!1,fixed:!0,playerId:"div[id^\x3d'vjs_video']:not([id$\x3d'_api']):not([id*\x3d'_component'])",quartile:!0,buffering:!0,beaconType:"auto",pctInc:25,pollRate:250,nameCallback:null,beaconCurve:{300:30,60:10,600:60,130:30,420:45,1800:150},pause:!0,preProcess:null,loadMeta:!0,screenMode:!0,beacon:!0,bins:15,beaconRate:60,volume:!0},tagMgr:{enable:!0,tagManager:"Google Tag Manager"},
heatmap:{enable:!0,maxymiserEnable:!0,selectorEngineType:"default",blockCollect:!0},cookieCutter:{readCookies:[{cookie:{TEST:"ora.cook_a"},options:{persist:!0}},{cookie:{ORA_FPC:{id:"ora.c_id",ss:"ora.c_ss",lv:"ora.c_lv"}},options:{parseOn:":",parseLv:"\x3d"}},{cookie:{ELOQUA:{GUID:"ora.elq.vid",FPCVISITED:"ora.eloqua_flag"}},options:{parseOn:"\x26",persist:!0}},{cookie:{utag_main:{_ss:"ora.u_ss",_st:"ora.u_st",v_id:"ora.u_vid",_sn:"ora.u_sn",ses_id:"ora.u_ses_id"}},options:{parseOn:"$",parseLv:":",
persist:!1}},{cookie:{WTPERSIST:{elqCid:"ora.elq.cid"}},options:{parseOn:"\x26",parseLv:"\x3d"}}],enable:!0},formTracking:{enable:!0,click_type:"mousedown",scroll_frequency:10,options:[{forms_to_track:[{interaction:!0,form_selector:"form",display_name:"my form",interaction_abandonment:!0,submit_selector:"button.submit",impression_abandonment:!0,impression:!0,form_submit:!0}]}]},msgListener:{domains:["http://my.site.com","https://mysite.com"],enable:!0},rdyEvt:{enable:!0,blockCollect:!0},sbt:{enable:!0,
eventList:[{url:{pattern:"",criteria:""},events:[{type:"",dom_selector:"",name:"",parameters:[{name:"",dom_selector:""},{name:"",value:""}]}]}]},optOutFooter:{background:"#DAA520",textColor:"#2f4f4f",optMsg:'This site uses cookies to analyze user activity in order to improve the Website.  See our \x3ca href\x3d#privacyPolicy\x3eprivacy policy\x3c/a\x3e for more information. You may opt-out of tracking for this site \x3cINPUT type\x3d"button" id\x3d"OptOut" style\x3d"background: gray; color: white;font-size:8pt" value\x3d"Opt Out" onclick\x3d"ORA.analytics.plugins.optOutFooter.optOut();"\x3e\x3c/button\x3e',
autoOptin:!0,optTime:15E3,enable:!0}},timezone:0,disableSSL:!1,defaultCollectionServer:"dc.oracleinfinity.io",s_useTrackingPipeline:!0,secureCookie:!0,FPCConfig:{name:"ORA_FPC",autoTLD:!0,sessionOnly:!1},destinations:[{accountGuid:"3635138d8e594c2c1be5bc1f505e5b30"}],s_TrackingPipelineTimeout:4E3};typeof ORA.analyticsModule.prototype.oraConfigObj.enabled&&!1===ORA.analyticsModule.prototype.oraConfigObj.enabled?ORA.Debug.debug("analytics  module disabled - exiting module setup"):(ORA.analyticsModule.prototype.preinit=
function(){try{ORA.Debug.debug("PREINIT: Executing Preinit script")}catch(k){ORA.abortModuleHelper("analytics",k)}},ORA.analyticsModule.prototype.init=function(){try{this.oraConfigObj.key="value",void 0===this.oraConfigObj.doLoad&&(this.oraConfigObj.doLoad=!0),this.oraConfigObj.doLoad=this.oraConfigObj.doLoad||this.oraConfigObj.alwaysLoad}catch(k){ORA.abortModuleHelper("analytics",k)}},ORA.analyticsModule.prototype.preload=function(){try{var k=0;ORA.analyticsModule.prototype.oraConfigObj.s_conversionTimeout&&
(k=ORA.analyticsModule.prototype.oraConfigObj.s_conversionTimeout);ORA.setLoaderConversionTimeoutDefault(Math.max(k,ORA.loaderConversionTimeoutDefault()));ORA.Debug.debug("PRELOAD:  Executing preload script")}catch(n){ORA.abortModuleHelper("analytics",n)}},ORA.analyticsModule.prototype.load=function(k){try{ORA.Debug.debug("LOAD:  Executing load phase"),ORA.downloadLib("head",k,function(){ORA.fireEvent(new ORA.Event("analytics_"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},0,!0,this.oraConfigObj.libUrl)}catch(n){ORA.abortModuleHelper("analytics",
n)}},ORA.analyticsModule.prototype.postload=function(){ORA.Debug.debug("POSTLOAD:  Executing postload analytics complete");try{ORA.Debug.info("LOADER:  ORA.analyticsModule.prototype: postload"),ORA.analytics.setup(ORA.analyticsModule.prototype.oraConfigObj)}catch(k){ORA.abortModuleHelper("analytics",k)}},ORA.analyticsModule.prototype.abort=function(){try{ORA.Debug.debug("ABORT:  Executing analyticsModule abort")}catch(k){ORA.abortModuleHelper("analytics",k)}});ORA.analyticsModule.ProductName="analytics";
ORA.registerPlugin(ORA.analyticsModule,"production")},function(){var k=!0;ORA.sizzleModule=function(){};ORA.sizzleModule.prototype.oraConfigObj={libUrl:"//d.oracleinfinity.io/infy/acs/common/js/lib/sizzle.min.js",doLoad:!0,s_dependencies:""};ORA.sizzleModule.setLoaded=function(n){k=n};ORA.sizzleModule.getLoaded=function(){return k};ORA.sizzleModule.prototype.load=function(n){try{ORA.updateDependencies("sizzle",this.oraConfigObj.s_dependencies),"undefined"===typeof JSON&&ORA.isDependency("sizzle")?
(ORA.Debug.debug("Sizzle not detected"),ORA.sizzleModule.setLoaded(!1),ORA.downloadLib("head",n,function(){ORA.abortModuleHelper("sizzle","failed to download sizzle")},0,!0,this.oraConfigObj.libUrl)):(ORA.sizzleModule.setLoaded(!0),ORA.setExecuteState("sizzle","ready"))}catch(r){ORA.abortModuleHelper("sizzle",r)}};ORA.sizzleModule.prototype.postload=function(){};ORA.sizzleModule.ProductName="sizzle";ORA.registerPlugin(ORA.sizzleModule,"default")}(),function(){var k=!0;ORA.jsonModule=function(){};
ORA.jsonModule.prototype.oraConfigObj={libUrl:"//d.oracleinfinity.io/infy/acs/common/js/lib/json2.js",doLoad:!0,s_dependencies:""};ORA.jsonModule.setLoaded=function(n){k=n};ORA.jsonModule.getLoaded=function(){return k};ORA.jsonModule.prototype.load=function(n){try{ORA.updateDependencies("json",this.oraConfigObj.s_dependencies),"undefined"===typeof JSON&&ORA.isDependency("json")?(ORA.Debug.debug("JSON not detected"),ORA.jsonModule.setLoaded(!1),ORA.downloadLib("head",n,function(){ORA.abortModuleHelper("json",
"failed to download json");ORA.abortModuleHelper("analytics","failed to download json")},0,!0,this.oraConfigObj.libUrl)):(ORA.jsonModule.setLoaded(!0),ORA.setExecuteState("json","ready"))}catch(r){ORA.abortModuleHelper("analytics",r)}};ORA.jsonModule.prototype.postload=function(){};ORA.jsonModule.ProductName="json";ORA.registerPlugin(ORA.jsonModule,"default")}(),function(){ORA.Event.BLUEKAI_DATA_READY="bluekai_data_ready";var k={},n=function(){};"undefined"===typeof Array.isArray&&(Array.isArray=
function(h){return"[object Array]"===Object.prototype.toString.call(h)});var r=function(h,I){var G=I||"",E;for(E in h)h.hasOwnProperty(E)&&(Array.isArray(h[E])?k["ora."+G+"_"+E]=h[E].join(";"):"object"===typeof h[E]?r(h[E],G+"_"+E):k["ora."+G+"_"+E]=h[E]);return null},x=function(h){var I=[],G;for(G in h)h.hasOwnProperty(G)&&(I.push(String(G)),I.push(encodeURIComponent(h[G])));return I.join(",")},t=function(h){h&&h.data&&"bluekai"===h.data.source&&(r(h.data,"odc"),"undefined"!==typeof ORA.setCookie?
ORA.setCookie("bluekai_uid_plugin",x(k),"; path\x3d/"):document.cookie="bluekai_uid_plugin\x3d"+x(k)+"; path\x3d/");n()},A=function(){window.addEventListener?window.addEventListener("message",t,!1):ORA.Debug.debug("bluekai reguires addEventListener support","LOADER-bluekai")};n=function(){ORA.Debug.debug("Removing postMessage lister for bluekai data","ANA-bluekai_uid_plugin");window.removeEventListener?window.removeEventListener("message",t):window.removeEvent?window.removeEvent("onmessage",t):ORA.Debug.debug("Browser does not support Removing messageListeners - exiting",
"ANA-bluekai_uid_plugin");ORA.fireEvent(new ORA.Event(ORA.Event.BLUEKAI_DATA_READY,ORA.Event.STATUS_SUCCESS))};ORA&&ORA.fireEvent&&ORA.Debug&&setTimeout(A,1);window.ORA.bkLoader=A}(),function(){ORA.commonModule=function(){};ORA.Event.COMMON_LOAD_COMPLETE="common_load_complete";ORA.Event.COMMON_ORA_PLUGINMGR_READY="common_ora_pluginmgr_ready";ORA.Event.COMMON_HOSTED_PLUGINMGR_READY="common_hosted_pluginmgr_ready";ORA.Event.COMMON_TRACKING_FLUSH="common_tracking_flush";ORA.Event.COMMON_COM_EXEC_REQ=
"common_com_exec_req";ORA.Event.COMMON_BEFORE_GETID="common_before_getid";ORA.Event.COMMON_GETID="common_get_id";ORA.Event.COMMON_PRODUCT_READY="common_product_ready";ORA.commonModule.prototype.oraConfigObj={libUrl:"//d.oracleinfinity.io/infy/acs/common/js/1.3.49/common.js",doLoad:!0,s_dependencies:"json:running"};ORA.commonModule.prototype.load=function(k){try{(!ORA.hasVal(ORA.common)||ORA.hasVal(ORA.common)&&!ORA.hasVal(ORA.common.TrackingPipeline))&&ORA.isDependency("common")&&ORA.downloadLib("head",
k,function(){ORA.fireEvent(new ORA.Event("common"+ORA.Event.LOADER_MODULE_ABORT,ORA.Event.STATUS_SUCCESS))},0,!0,this.oraConfigObj.libUrl)}catch(n){ORA.abortModuleHelper("common",n)}};ORA.commonModule.prototype.postload=function(){ORA.common.setup()};ORA.commonModule.ProductName="common";ORA.registerPlugin(ORA.commonModule,"default")}(),function(){ORA.Event.ANA_LOAD_COMPLETE="analytics_load_complete";ORA.Event.ANA_ORA_PLUGINS_LOADED="analytics_ora_plugins_loaded";ORA.Event.ANA_HOSTED_PLUGINS_LOADED=
"analytics_hosted_plugins_loaded";ORA.Event.ANA_ORA_PLUGINS_INIT="analytics_ora_plugins_init";ORA.Event.ANA_HOSTED_PLUGINS_INIT="analytics_hosted_plugins_init";ORA.Event.ANA_DCS_SETUP="analytics_dcs_setup";ORA.Event.ANA_PRODUCT_READY="analytics_product_ready";ORA.Event.ANA_SETUP_COMPLETE="analytics_setup_complete";ORA.Event.ANA_BEFORE_PAGE_ANALYSIS="analytics_before_page_analysis";ORA.Event.ANA_AFTER_PAGE_ANALYSIS="analytics_after_page_analysis";ORA.Event.ANA_BEFORE_GETID="analytics_before_getid";
ORA.Event.ANA_AFTER_GETID="analytics_after_getid";ORA.Event.ANA_PV_MUTATE="analytics_pv_mutate";ORA.Event.ANA_DATA_SEND="analytics_data_send";ORA.Event.LOADER_CLICK="loader_click";ORA.Event.LOADER_PRE_EXECUTE="loader_pre_execute";ORA.Event.LOADER_EXECUTE="loader_execute";ORA.Event.LOADER_RESET="loader_reset";ORA.Event.LOADER_COLLECT="loader_collect";ORA.Event.LOADER_VIEW="loader_view";ORA.getContextName=function(){return ORA.getProduct("analytics")&&ORA.getProduct("analytics").configName||""};ORA.getConfigName=
function(){return ORA.getProduct("analytics")&&ORA.getProduct("analytics").configName||""};var k=function(n,r){ORA.fireEvent(new ORA.Event(n,ORA.Event.STATUS_SUCCESS,null,r),null,null,!0)};ORA.collect=function(n){k(ORA.Event.LOADER_COLLECT,n);return!0};ORA.view=function(n){k(ORA.Event.LOADER_VIEW,n);return!0};ORA.click=ORA.sendEvent=function(n){k(ORA.Event.LOADER_CLICK,n);return!0};ORA.regPlugin=function(n,r,x){var t=function(){ORA.Debug.debug("regPlugin - call of deferred register of "+n,"LOADER");
void 0===ORA.analytics.plugins[n]?(ORA.Debug.debug("Registering init for "+n),ORA.common.pluginMgr._regPlugin(n,r,x)):ORA.analytics.plugins[n]&&ORA.analytics.plugins[n].src?(ORA.analytics.plugins[n].loaded=!0,ORA.common.hostedPluginMgr._regPlugin(n,r,x,"hosted-plugins")):ORA.common.pluginMgr._regPlugin(n,r,x)};ORA.common&&ORA.common.pluginMgr&&ORA.common.pluginMgr.isReady&&!0===ORA.common.pluginMgr.isReady()?(ORA.Debug.debug("ORA.common.pluginMgr exists so register is possible"),t()):(ORA.Debug.debug("regPlugin - deferred register of "+
n,"LOADER"),ORA.analytics.plugins[n]&&ORA.analytics.plugins[n].src?ORA.addEventHandler(ORA.Event.COMMON_HOSTED_PLUGINMGR_READY,t,null,!0):ORA.addEventHandler(ORA.Event.COMMON_ORA_PLUGINMGR_READY,t,null,!0))};ORA.setUserParameter=function(n,r){if("string"===typeof n&&"string"===typeof r){var x={};x[n]=r;return ORA.setUserParameters(x)}ORA.Debug.error("Invalid user parameters are passed. Either key or value passed is null.");return!1};ORA.setUserParameters=function(n){try{if("object"===typeof n&&0<
Object.keys(n).length){var r={};Object.keys(n).forEach(function(x){if("string"===typeof n[x]||"number"===typeof n[x]||"boolean"===typeof n[x])r["user."+x]=n[x];else return ORA.Debug.error("Invalid value type in the user parameter json object for key"+x+"Only string values are accepted."),!1});r["wt.dl"]="51";r.dcsuri=window.location.pathname;r["wt.ev"]="userParams";r["wt.sys"]="userParams";return ORA.click({data:r})}ORA.Debug.error("Invalid user parameters are passed. The object passed is invalid or null.");
return!1}catch(x){return ORA.Debug.error("Invalid user parameters are passed. The object passed is invalid or null."),!1}}}(),function(){ORA.responsysModule=function(){};ORA.responsysModule.prototype.oraConfigObj={doLoad:!0,s_dependencies:"",config:{cookie_name:"responsys_cookie_default",fallback_cookie_domain_level:0,fallback_timeout:"2000",urlSuffix:"/pub/cc",responsysURL:"",additionalParms:"_pb_\x3dR\x26_tt_\x3dQ"}};ORA.responsysModule.prototype.moveAndToResp=function(k,n){for(var r in k.config)k.config.hasOwnProperty(r)&&
""!==k.config[r]&&(n.config[r]=k.config[r])};ORA.responsysModule.prototype.validateSettings=function(k){k.config.responsysURL||(ORA.debug("missing required setting for responsysURL, disabling module","responsys"),k.enabled=!1)};ORA.responsysModule.prototype.postload=function(){var k=function(){ORA.Debug.debug("responsysModule load pixel failed - fallback to standard cookie",ORA.responsysModule.ProductName);ORA.responsysModule.prototype.cookieFallback()},n=function(){ORA.Debug.debug("responsysModule load pixel success",
ORA.responsysModule.ProductName)};try{if(this.responsysExists()){var r=this.prepareUrl()+this.removeParameterList(location.search,this.oraConfigObj.config.additionalParms);r+="\x26"+this.oraConfigObj.config.additionalParms+location.hash;this.responsysLoadPixel(r,n,k,this.oraConfigObj.config.fallback_timeout);return!0}ORA.setExecuteState("responsysModule","ready")}catch(x){return ORA.Debug.debug("responsysModule load error "+x.message),!1}};ORA.responsysModule.prototype.load=function(){try{var k={};
if(ORA.analyticsModule&&ORA.analyticsModule.prototype&&ORA.analyticsModule.prototype.oraConfigObj&&ORA.analyticsModule.prototype.oraConfigObj.responsys){var n=ORA.responsysModule.prototype.oraConfigObj;k=ORA.analyticsModule.prototype.oraConfigObj.responsys;k.doLoad&&(n.doLoad=k.doLoad);k.s_dependencies&&(n.s_dependencies=k.s_dependencies);ORA.responsysModule.prototype.moveAndToResp(k,n);ORA.responsysModule.prototype.validateSettings(k)}void 0!==k.enabled&&k.enabled?(ORA.updateDependencies("responsysModule",
"analytics:downloading"),ORA.setExecuteState("responsysModule","ready")):ORA.debug("responsys module not enabled","responsys")}catch(r){ORA.Debug.debug("responsysModule load error "+r.message)}};ORA.responsysModule.prototype.responsysExists=function(k){k=ORA.parseQueryString(k);return!!(k&&k._ri_&&k._ei_)};ORA.responsysModule.prototype.responsysLoadPixel=function(k,n,r,x){var t=new Image,A=!1;t.onload=function(){A||(A=!0,n(),ORA.Debug.debug("Responsys pixel loaded",ORA.responsysModule.ProductName))};
t.onerror=function(){A||(A=!0,r(),ORA.Debug.debug("Responsys pixel load failed",ORA.responsysModule.ProductName))};window.setTimeout(function(){A&&1!==x||(A=!0,ORA.Debug.debug("Responsys pixel load failed",ORA.responsysModule.ProductName),r())},x);t.src=k};ORA.responsysModule.prototype.cookieFallback=function(k){var n=ORA.parseQueryString(k),r=this.oraConfigObj.config;k=r.cookie_name;n="_ri_"+n._ri_+"\x26_ei_"+n._ei_;var x=location.hostname.split(".");r=r.fallback_cookie_domain_level;var t=new Date,
A="";for(t.setTime(t.getTime()+63113851500);r;)x.shift(),r--;x.join(".")!==location.host&&(A=";domain\x3d"+x.join("."));x="; path\x3d/ ; expires\x3d "+t.toGMTString()+A;ORA.Debug.debug("Setting fallback cookie","responsysModule");ORA.setCookie(k,n,x)};ORA.responsysModule.prototype.removeParameter=function(k,n){var r=k.split("?");if(2<=r.length){for(var x=encodeURIComponent(n)+"\x3d",t=r[1].split(/[&;]/g),A=t.length;0<A;)A--,-1!==t[A].lastIndexOf(x,0)&&t.splice(A,1);return 0<t.length?r[0]+t.join("\x26"):
r[0]}return k};ORA.responsysModule.prototype.removeParameterList=function(k,n){for(var r=k,x=n.split("\x26"),t=0;t<x.length;t++){var A=x[t].split("\x3d");r=this.removeParameter(r,A[0])}return"?"+r};ORA.responsysModule.prototype.prepareUrl=function(){var k=this.oraConfigObj.config,n=k.responsysURL;k.urlBase&&""!==k.urlBase&&(n=k.urlBase);return n+k.urlSuffix};ORA.responsysModule.ProductName="responsysModule";ORA.registerPlugin(ORA.responsysModule,"default")}(),ORA.productLoadInit(),ORA.start()))})();